// <auto-generated />
using System;
using LearnTeach.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnTeach.Infrastructure.Migrations
{
    [DbContext(typeof(LEANRANDTEACHContext))]
    partial class LEANRANDTEACHContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnTeach.Domain.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRating")
                        .HasColumnType("int");

                    b.Property<int>("MinRating")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Categoriess", b =>
                {
                    b.Property<int>("CateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CateId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CateId")
                        .HasName("PK__CATEGORI__27638D14D2BAC615");

                    b.ToTable("CATEGORIESS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Certificate", b =>
                {
                    b.Property<int>("Cerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CERID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cerid"));

                    b.Property<string>("Cername")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("CERName");

                    b.Property<string>("Cerpic")
                        .IsRequired()
                        .HasMaxLength(350)
                        .IsUnicode(false)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("CERPic");

                    b.Property<int?>("EarnedYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(datepart(year,getdate()))");

                    b.Property<string>("InstatutionName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Cerid")
                        .HasName("PK__CERTIFIC__5D4205583D8E74AF");

                    b.ToTable("CERTIFICATES", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Chatthread", b =>
                {
                    b.Property<int>("ChatThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatThreadId"));

                    b.Property<Guid>("AzureThreadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime");

                    b.Property<string>("LastMessagePreview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("ChatThreadId")
                        .HasName("PK__CHATTHRE__32405D65FD56707D");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("CHATTHREAD", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__COMMENTS__C3B4DFCAD68DFD97");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("COMMENTS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Diamond", b =>
                {
                    b.Property<int>("Diamondid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DIAMONDID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Diamondid"));

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Diamondid")
                        .HasName("PK__DIAMOND__0E6908ED2F4448F3");

                    b.HasIndex(new[] { "UserId" }, "UQ__DIAMOND__1788CC4DF3A3B250")
                        .IsUnique();

                    b.ToTable("DIAMOND", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.DiamondPackage", b =>
                {
                    b.Property<int>("DiamondPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiamondPackageId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiamondAmount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiamondPackageId");

                    b.ToTable("DiamondPackages");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.DiamondTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiamondPackageId")
                        .HasColumnType("int");

                    b.Property<int>("PointsChanged")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiamondPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("DiamondTransactions");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Feedback", b =>
                {
                    b.Property<int>("Feedbackid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FEEDBACKID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Feedbackid"));

                    b.Property<string>("Feedbackdetails")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("FEEDBACKDETAILS");

                    b.Property<int>("Feedbackrange")
                        .HasColumnType("int")
                        .HasColumnName("FEEDBACKRANGE");

                    b.HasKey("Feedbackid")
                        .HasName("PK__FEEDBACK__7074B31EE5D386DA");

                    b.ToTable("FEEDBACK", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Like", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"));

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LikeId")
                        .HasName("PK__LIKES__A2922C147C9BB08F");

                    b.HasIndex("PostId");

                    b.HasIndex(new[] { "UserId", "PostId" }, "UQ_Like")
                        .IsUnique();

                    b.ToTable("LIKES", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Material", b =>
                {
                    b.Property<int>("Materialid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATERIALID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Materialid"));

                    b.Property<int>("Cateid")
                        .HasColumnType("int")
                        .HasColumnName("CATEID");

                    b.Property<string>("Description")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TITLE");

                    b.Property<int>("Uploaderid")
                        .HasColumnType("int")
                        .HasColumnName("UPLOADERID");

                    b.HasKey("Materialid")
                        .HasName("PK__MATERIAL__278B51D52BAE0509");

                    b.HasIndex("Cateid");

                    b.HasIndex("Uploaderid");

                    b.ToTable("MATERIALS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("RedirectURL");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__NOTIFICA__20CF2E126A589282");

                    b.HasIndex("SenderId");

                    b.HasIndex("UserId");

                    b.ToTable("NOTIFICATIONS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Package", b =>
                {
                    b.Property<int>("Packageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PACKAGEId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Packageid"));

                    b.Property<int>("Diamondpoints")
                        .HasColumnType("int")
                        .HasColumnName("DIAMONDPoints");

                    b.Property<string>("Packagedetails")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("PACKAGEDETAILS");

                    b.Property<string>("Packageduration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PACKAGEDURATION");

                    b.Property<string>("Packagename")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("PACKAGENAME");

                    b.Property<decimal>("Packageprice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PACKAGEPrice");

                    b.HasKey("Packageid")
                        .HasName("PK__PACKAGE__35387D5009B32069");

                    b.ToTable("PACKAGE", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Paymenttransaction", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CURRENCY");

                    b.Property<string>("GetwayTransactionId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GetwayTransactionID");

                    b.Property<bool?>("Mastercard")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<DateOnly?>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Visa")
                        .HasColumnType("bit");

                    b.HasKey("PayId")
                        .HasName("PK__PAYMENTT__EE8FCECF6395CEC7");

                    b.ToTable("PAYMENTTRANSACTION", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int?>("CategoriessCateId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.Property<int>("TotalComments")
                        .HasColumnType("int");

                    b.Property<int>("TotalLiked")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.HasKey("PostId")
                        .HasName("PK__POSTS__AA12603883BF519D");

                    b.HasIndex("CategoriessCateId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId");

                    b.ToTable("POSTS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Postmedia", b =>
                {
                    b.Property<int>("PmediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PMediaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PmediaId"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("PostID");

                    b.HasKey("PmediaId")
                        .HasName("PK__POSTMEDI__6414C455D155CFFB");

                    b.HasIndex("PostId");

                    b.ToTable("POSTMEDIAS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.PremiumSubscriber", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SubscribedAt")
                        .HasColumnType("date");

                    b.HasKey("UserId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("PremiumSubscriber", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectDesc")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Repolink")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("REPOLink");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId")
                        .HasName("PK__PROJECTS__761ABED038F8DFCE");

                    b.HasIndex("UserId");

                    b.ToTable("PROJECTS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReportDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ReportedUserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId")
                        .HasName("PK__REPORTS__D5BD4805BCF300B0");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ReportedUserId");

                    b.ToTable("REPORTS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Session", b =>
                {
                    b.Property<int>("Sessionid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SESSIONId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sessionid"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("EndedNotificationSent")
                        .HasColumnType("bit");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<bool>("LearnerReminderSent")
                        .HasColumnType("bit");

                    b.Property<bool>("PointsApplied")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduleEnd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ScheduleStart")
                        .HasColumnType("datetime");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.Property<bool>("StartedNotificationSent")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("StudentJoined")
                        .HasColumnType("bit");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("TeacherJoined")
                        .HasColumnType("bit");

                    b.Property<bool>("TeacherReminderSent")
                        .HasColumnType("bit");

                    b.Property<bool>("UpcomingNotificationSent")
                        .HasColumnType("bit");

                    b.Property<string>("ZoomJoinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZoomMeetingId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sessionid")
                        .HasName("PK__SESSION__FC86FC5F062580BD");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SkillId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SESSION", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int?>("CateId")
                        .HasColumnType("int")
                        .HasColumnName("CateID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SkillId")
                        .HasName("PK__SKILLS__DFA09187E37E63C6");

                    b.HasIndex("CateId");

                    b.ToTable("SKILLS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Socialmediaaccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("FacebookLink")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Linkedin")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("PersonalWebsite")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId")
                        .HasName("PK__SOCIALME__349DA5A65744A42F");

                    b.HasIndex("UserId");

                    b.ToTable("SOCIALMEDIAACCOUNTS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserDiamondPackage", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DiamondPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "DiamondPackageId");

                    b.HasIndex("DiamondPackageId");

                    b.ToTable("UserDiamondPackage");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserPayment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PayId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PayId");

                    b.HasIndex("PayId");

                    b.ToTable("UserPayments");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserSkills", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("GoodAtIt")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Userfeedback", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "FeedbackId")
                        .HasName("PK_UserFeedback");

                    b.HasIndex("FeedbackId");

                    b.ToTable("USERFEEDBACK", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usernationalid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackPic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FrontPic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SelfieWithId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__USERNATI__3214EC078DE172F2");

                    b.HasIndex(new[] { "UserId" }, "UQ__USERNATI__1788CC4DF7CCB5C3")
                        .IsUnique();

                    b.ToTable("USERNATIONALID", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usersessionfeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("RatedToUserId")
                        .HasColumnType("int");

                    b.Property<int>("RatingValue")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId")
                        .HasName("PK__USERSESS__6A4BEDD62089FA43");

                    b.HasIndex("RatedByUserId");

                    b.HasIndex("RatedToUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("USERSESSIONFEEDBACKS", (string)null);
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usersprofile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Authuserid")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("AUTHUSERID");

                    b.Property<int?>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExperienceText")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfilePic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__USERSPRO__1788CC4C54A710E3");

                    b.HasIndex("BadgeId");

                    b.ToTable("USERSPROFILE", (string)null);
                });

            modelBuilder.Entity("PackageUsersprofile", b =>
                {
                    b.Property<int>("PackagesPackageid")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("PackagesPackageid", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("PackageUsersprofile");
                });

            modelBuilder.Entity("PaymenttransactionUsersprofile", b =>
                {
                    b.Property<int>("PaysPayId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("PaysPayId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("PaymenttransactionUsersprofile");
                });

            modelBuilder.Entity("SkillUsersprofile", b =>
                {
                    b.Property<int>("SkillsSkillId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("SkillsSkillId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("SkillUsersprofile");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Chatthread", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User1")
                        .WithMany("ChatthreadUser1s")
                        .HasForeignKey("User1Id")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_User1");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User2")
                        .WithMany("ChatthreadUser2s")
                        .HasForeignKey("User2Id")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_User2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Comment", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Comment_Post");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Comment_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Diamond", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithOne("Diamond")
                        .HasForeignKey("LearnTeach.Domain.Models.Diamond", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Diamond");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.DiamondTransaction", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.DiamondPackage", "DiamondPackage")
                        .WithMany("DiamondTransactions")
                        .HasForeignKey("DiamondPackageId");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Users")
                        .WithMany("DiamondTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiamondPackage");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Like", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Like_Post");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Like_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Material", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Categoriess", "Cate")
                        .WithMany("Materials")
                        .HasForeignKey("Cateid")
                        .IsRequired()
                        .HasConstraintName("FK_Material_Category");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Uploader")
                        .WithMany("Materials")
                        .HasForeignKey("Uploaderid")
                        .IsRequired()
                        .HasConstraintName("FK_Material_User");

                    b.Navigation("Cate");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Notification", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Sender")
                        .WithMany("NotificationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Notification_Sender");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("Sender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Post", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Categoriess", "Categoriess")
                        .WithMany()
                        .HasForeignKey("CategoriessCateId");

                    b.HasOne("LearnTeach.Domain.Models.Skill", "Skill")
                        .WithMany("Posts")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_Skill");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Post_User");

                    b.Navigation("Categoriess");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Postmedia", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Post", "Post")
                        .WithMany("PostMedias")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_PostMedia_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.PremiumSubscriber", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Package", "Package")
                        .WithMany("PremiumSubscribers")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_PremiumSubscriber_Package");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Users")
                        .WithMany("PremiumSubscribers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PremiumSubscriber_User");

                    b.Navigation("Package");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Project", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Report", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "ReportedByNavigation")
                        .WithMany("ReportReportedByNavigations")
                        .HasForeignKey("ReportedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Report_By");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "ReportedUser")
                        .WithMany("ReportReportedUsers")
                        .HasForeignKey("ReportedUserId")
                        .HasConstraintName("FK_Report_User");

                    b.Navigation("ReportedByNavigation");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Session", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Learner")
                        .WithMany("SessionLearners")
                        .HasForeignKey("LearnerId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Learner");

                    b.HasOne("LearnTeach.Domain.Models.Skill", "Skill")
                        .WithMany("Sessions")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Skill");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Teacher")
                        .WithMany("SessionTeachers")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_Session_Teacher");

                    b.Navigation("Learner");

                    b.Navigation("Skill");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Skill", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Categoriess", "Cate")
                        .WithMany("Skills")
                        .HasForeignKey("CateId")
                        .HasConstraintName("FK_Skill_Category");

                    b.Navigation("Cate");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Socialmediaaccount", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Socialmediaaccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_SocialMedia_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserDiamondPackage", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.DiamondPackage", "DiamondPackage")
                        .WithMany("UserDiamondPackages")
                        .HasForeignKey("DiamondPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("UserDiamondPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiamondPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserPayment", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Paymenttransaction", "Paymenttransaction")
                        .WithMany("UserPayments")
                        .HasForeignKey("PayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "Users")
                        .WithMany("UserPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paymenttransaction");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.UserSkills", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Userfeedback", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Feedback", "Feedback")
                        .WithMany("Userfeedbacks")
                        .HasForeignKey("FeedbackId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFeedback_Feedback");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithMany("Userfeedbacks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserFeedback_User");

                    b.Navigation("Feedback");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usernationalid", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "User")
                        .WithOne("Usernationalid")
                        .HasForeignKey("LearnTeach.Domain.Models.Usernationalid", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserNationalID_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usersessionfeedback", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "RatedByUser")
                        .WithMany("UsersessionfeedbackRatedByUsers")
                        .HasForeignKey("RatedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_ByUser");

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", "RatedToUser")
                        .WithMany("UsersessionfeedbackRatedToUsers")
                        .HasForeignKey("RatedToUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_ToUser");

                    b.HasOne("LearnTeach.Domain.Models.Session", "Session")
                        .WithMany("Usersessionfeedbacks")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Session");

                    b.Navigation("RatedByUser");

                    b.Navigation("RatedToUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usersprofile", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Badge", "Badge")
                        .WithMany("Users")
                        .HasForeignKey("BadgeId");

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("PackageUsersprofile", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Package", null)
                        .WithMany()
                        .HasForeignKey("PackagesPackageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PaymenttransactionUsersprofile", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Paymenttransaction", null)
                        .WithMany()
                        .HasForeignKey("PaysPayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillUsersprofile", b =>
                {
                    b.HasOne("LearnTeach.Domain.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnTeach.Domain.Models.Usersprofile", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Badge", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Categoriess", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.DiamondPackage", b =>
                {
                    b.Navigation("DiamondTransactions");

                    b.Navigation("UserDiamondPackages");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Feedback", b =>
                {
                    b.Navigation("Userfeedbacks");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Package", b =>
                {
                    b.Navigation("PremiumSubscribers");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Paymenttransaction", b =>
                {
                    b.Navigation("UserPayments");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("PostMedias");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Session", b =>
                {
                    b.Navigation("Usersessionfeedbacks");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Skill", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Sessions");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("LearnTeach.Domain.Models.Usersprofile", b =>
                {
                    b.Navigation("ChatthreadUser1s");

                    b.Navigation("ChatthreadUser2s");

                    b.Navigation("Comments");

                    b.Navigation("Diamond");

                    b.Navigation("DiamondTransactions");

                    b.Navigation("Likes");

                    b.Navigation("Materials");

                    b.Navigation("NotificationSenders");

                    b.Navigation("NotificationUsers");

                    b.Navigation("Posts");

                    b.Navigation("PremiumSubscribers");

                    b.Navigation("Projects");

                    b.Navigation("ReportReportedByNavigations");

                    b.Navigation("ReportReportedUsers");

                    b.Navigation("SessionLearners");

                    b.Navigation("SessionTeachers");

                    b.Navigation("Socialmediaaccounts");

                    b.Navigation("UserDiamondPackages");

                    b.Navigation("UserPayments");

                    b.Navigation("UserSkills");

                    b.Navigation("Userfeedbacks");

                    b.Navigation("Usernationalid");

                    b.Navigation("UsersessionfeedbackRatedByUsers");

                    b.Navigation("UsersessionfeedbackRatedToUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
