// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Categoriess
{
    public int CateId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Material> Materials { get; set; } = new List<Material>();

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}