// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Certificate
{
    public int Cerid { get; set; }

    public int UserId { get; set; }

    public string Cername { get; set; }

    public string InstatutionName { get; set; }

    public int? EarnedYear { get; set; }

    public string Cerpic { get; set; }
}