// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Chatthread
{
    public int ChatThreadId { get; set; }

    public Guid AzureThreadId { get; set; }

    public int User1Id { get; set; }

    public int User2Id { get; set; }

    public string LastMessagePreview { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public bool? IsBlocked { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Usersprofile User1 { get; set; }

    public virtual Usersprofile User2 { get; set; }
}