// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Diamond
{
    public int Diamondid { get; set; }

    public int UserId { get; set; }

    public int TotalPoints { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Usersprofile User { get; set; }

    //public string ReasonofUpdate { get; set; }

    //public int? PaymentTransactionId { get; set; }

    //public virtual Paymenttransaction PaymentTransaction { get; set; }


}