// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Feedback
{
    public int Feedbackid { get; set; }

    public int Feedbackrange { get; set; }

    public string Feedbackdetails { get; set; }

    public virtual ICollection<Userfeedback> Userfeedbacks { get; set; } = new List<Userfeedback>();
}