// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Like
{
    public int LikeId { get; set; }

    public int UserId { get; set; }

    public int PostId { get; set; }

    public virtual Post Post { get; set; }

    public virtual Usersprofile User { get; set; }
}

