// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Material
{
    public int Materialid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Cateid { get; set; }

    public int Uploaderid { get; set; }

    public string? FileUrl { get; set; }

    public virtual Categoriess Cate { get; set; }

    public virtual Usersprofile Uploader { get; set; }
}