// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string Title { get; set; }

    public string Details { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public int? EntityId { get; set; }

    public string EntityType { get; set; }

    public string RedirectUrl { get; set; }

    public int UserId { get; set; }

    public int? SenderId { get; set; }

    public virtual Usersprofile Sender { get; set; }

    public virtual Usersprofile User { get; set; }
}