// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Package
{
    public int Packageid { get; set; }

    public string Packagename { get; set; }

    public string Packagedetails { get; set; }

    public string Packageduration { get; set; }

    public int Diamondpoints { get; set; }

    public decimal Packageprice { get; set; }

    public virtual ICollection<Usersprofile> Users { get; set; } = new List<Usersprofile>();

    // Navigation
    public ICollection<PremiumSubscriber> PremiumSubscribers { get; set; }

}