// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LearnTeach.Domain.Models;

public partial class Paymenttransaction
{
    public int PayId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    [Column(TypeName = "nvarchar(MAX)")]
    public string? Token { get; set; }  // السماح بـ NULL باستخدام ?
    public string Status { get; set; }

    public bool? Mastercard { get; set; }

    public bool? Visa { get; set; }

    public string GetwayTransactionId { get; set; }

    public DateOnly? TransactionDate { get; set; }

    //  public virtual ICollection<Diamond> Diamonds { get; set; } = new List<Diamond>();

    public virtual ICollection<Usersprofile> Users { get; set; } = new List<Usersprofile>();

    // Navigation
    public ICollection<UserPayment> UserPayments { get; set; }
}