// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Post
{
    public int PostId { get; set; }

    public string Content { get; set; }

    //public DateTime? CreatedAt { get; set; }
    public DateTime? CreatedAt { get; set; } = DateTime.UtcNow;


    public int TotalLiked { get; set; } 

    public int TotalComments { get; set; }

    public int UserId { get; set; }

    public int SkillId { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual ICollection<Postmedia> PostMedias { get; set; } = new List<Postmedia>();

    public int categoryId { get; set; }
    public Categoriess Categoriess { get; set; }

    public virtual Skill Skill { get; set; }

    public virtual Usersprofile User { get; set; }
}


