// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Postmedia
{
    public int PmediaId { get; set; }

    public string MediaUrl { get; set; }

    public string EntityType { get; set; }

    public int PostId { get; set; }

    public virtual Post Post { get; set; }
}



