// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Project
{
    public int ProjectId { get; set; }

    public int UserId { get; set; }

    public string ProjectName { get; set; }

    public string Repolink { get; set; }

    public string ProjectDesc { get; set; }

    public virtual Usersprofile User { get; set; }
}