// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Report
{
    public int ReportId { get; set; }

    public string ReportDescription { get; set; }

    public string EntityType { get; set; }

    public int EntityId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int ReportedBy { get; set; }

    public int? ReportedUserId { get; set; }
    public string ReportStatus { get; set; } = "Pending"; // Pending, Approved, Rejected


    public virtual Usersprofile ReportedByNavigation { get; set; }

    public virtual Usersprofile ReportedUser { get; set; }
}