// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Skill
{

    public int SkillId { get; set; }
    public string Name { get; set; }
    public int? CateId { get; set; }
    public virtual Categoriess Cate { get; set; }

    public virtual ICollection<UserSkills> UserSkills { get; set; } = new List<UserSkills>();
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
    public ICollection<Usersprofile> Users { get; set; } = new List<Usersprofile>();

}