// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Socialmediaaccount
{
    public int AccountId { get; set; }

    public int UserId { get; set; }

    public string FacebookLink { get; set; }

    public string Linkedin { get; set; }

    public string PersonalWebsite { get; set; }

    public virtual Usersprofile User { get; set; }
}