// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Usersessionfeedback
{
    public int FeedbackId { get; set; }

    public int RatingValue { get; set; }

    public string Comment { get; set; }

    public int RatedByUserId { get; set; }

    public int RatedToUserId { get; set; }

    public int SessionId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Usersprofile RatedByUser { get; set; }

    public virtual Usersprofile RatedToUser { get; set; }

    public virtual Session Session { get; set; }
}