// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Userfeedback
{
    public int UserId { get; set; }

    public int FeedbackId { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual Feedback Feedback { get; set; }

    public virtual Usersprofile User { get; set; }
}