// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Usersprofile
{
    public int UserId { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string ExperienceText { get; set; }

    public string ProfilePic { get; set; }
    public string Status { get; set; }="active"; // active, susbended
    public DateOnly? CreatedAt { get; set; }
    public string Authuserid { get; set; }

    public virtual Diamond Diamond { get; set; }



    public virtual ICollection<Chatthread> ChatthreadUser1s { get; set; } = new List<Chatthread>();

    public virtual ICollection<Chatthread> ChatthreadUser2s { get; set; } = new List<Chatthread>();

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    

    public virtual ICollection<Like> Likes { get; set; } = new List<Like>();

    public virtual ICollection<Material> Materials { get; set; } = new List<Material>();

    public virtual ICollection<Notification> NotificationSenders { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationUsers { get; set; } = new List<Notification>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Report> ReportReportedByNavigations { get; set; } = new List<Report>();

    public virtual ICollection<Report> ReportReportedUsers { get; set; } = new List<Report>();

    public virtual ICollection<Session> SessionLearners { get; set; } = new List<Session>();

    public virtual ICollection<Session> SessionTeachers { get; set; } = new List<Session>();

    public virtual ICollection<Socialmediaaccount> Socialmediaaccounts { get; set; } = new List<Socialmediaaccount>();

    public virtual ICollection<Userfeedback> Userfeedbacks { get; set; } = new List<Userfeedback>();

    public virtual Usernationalid Usernationalid { get; set; }

    public virtual ICollection<Usersessionfeedback> UsersessionfeedbackRatedByUsers { get; set; } = new List<Usersessionfeedback>();

    public virtual ICollection<Usersessionfeedback> UsersessionfeedbackRatedToUsers { get; set; } = new List<Usersessionfeedback>();

    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    public virtual ICollection<Paymenttransaction> Pays { get; set; } = new List<Paymenttransaction>();

    public virtual ICollection<UserSkills> UserSkills { get; set; } = new List<UserSkills>();

    public ICollection<DiamondTransaction> DiamondTransactions { get; set; }


    // Navigation Properties
    public virtual ICollection<UserDiamondPackage> UserDiamondPackages { get; set; } = new List<UserDiamondPackage>();
    public ICollection<UserPayment> UserPayments { get; set; }
    public ICollection<PremiumSubscriber> PremiumSubscribers { get; set; }



    //Badge Relationship
    public int? BadgeId { get; set; }
    public virtual Badge? Badge { get; set; }
    public ICollection<Skill> Skills { get; set; } = new List<Skill>();
}

