// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LearnTeach.Domain.Models;

public partial class Usernationalid
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string FrontPic { get; set; }

    public string BackPic { get; set; }

    public string SelfieWithId { get; set; }

    // Vertification Status
    public string VerificationStatus { get; set; } = "Pending"; // Pending, Approved, Rejected
    public DateTime? SubmittedAt { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public string? RejectionReason { get; set; }

    public virtual Usersprofile User { get; set; }
}