// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using LearnTeach.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace LearnTeach.Infrastructure.Data;

public partial class LEANRANDTEACHContext : DbContext
{
    public LEANRANDTEACHContext(DbContextOptions<LEANRANDTEACHContext> options)
        : base(options)
    {
    }
    public virtual DbSet<Badge> Badges { get; set; }


    public virtual DbSet<Categoriess> Categoriesses { get; set; }

    public virtual DbSet<Certificate> Certificates { get; set; }

    public virtual DbSet<Chatthread> Chatthreads { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Diamond> Diamonds { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Like> Likes { get; set; }

    public virtual DbSet<Material> Materials { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<Paymenttransaction> Paymenttransactions { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<Postmedia> Postmedias { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Report> Reports { get; set; }

    public virtual DbSet<Session> Sessions { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    public virtual DbSet<Socialmediaaccount> Socialmediaaccounts { get; set; }

    public virtual DbSet<Userfeedback> Userfeedbacks { get; set; }

    public DbSet<PremiumSubscriber> PremiumSubscribers { get; set; }

    public virtual DbSet<Usernationalid> Usernationalids { get; set; }

    public virtual DbSet<Usersessionfeedback> Usersessionfeedbacks { get; set; }

    public virtual DbSet<Usersprofile> Usersprofiles { get; set; }

    public DbSet<UserPayment> UserPayments { get; set; }

    public DbSet<DiamondTransaction> DiamondTransactions { get; set; }

    public DbSet<DiamondPackage> DiamondPackages { get; set; }
    public DbSet<UserSkills> UserSkills { get; set; }
    public DbSet<ChatMessage> ChatMessages { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        



        modelBuilder.Entity<UserPayment>()
            .HasKey(up => new { up.UserId, up.PayId });

        modelBuilder.Entity<UserPayment>()
            .HasOne(up => up.Users)
            .WithMany(u => u.UserPayments)
            .HasForeignKey(up => up.UserId);

        modelBuilder.Entity<UserPayment>()
            .HasOne(up => up.Paymenttransaction)
            .WithMany(pt => pt.UserPayments)
            .HasForeignKey(up => up.PayId);


        modelBuilder.Entity<DiamondTransaction>()
            .HasOne(dt => dt.Users)
            .WithMany(u => u.DiamondTransactions)
            .HasForeignKey(dt => dt.UserId);

        modelBuilder.Entity<DiamondTransaction>()
               .HasOne(dt => dt.DiamondPackage)
               .WithMany(dp => dp.DiamondTransactions)
               .HasForeignKey(dt => dt.DiamondPackageId);



        modelBuilder.Entity<UserDiamondPackage>()
    .HasKey(udp => new { udp.UserId, udp.DiamondPackageId });

        modelBuilder.Entity<UserDiamondPackage>()
            .HasOne(udp => udp.User)
            .WithMany(u => u.UserDiamondPackages)
            .HasForeignKey(udp => udp.UserId);

        modelBuilder.Entity<UserDiamondPackage>()
            .HasOne(udp => udp.DiamondPackage)
            .WithMany(dp => dp.UserDiamondPackages)
            .HasForeignKey(udp => udp.DiamondPackageId);


        modelBuilder.Entity<Categoriess>(entity =>
        {
            entity.HasKey(e => e.CateId).HasName("PK__CATEGORI__27638D14D2BAC615");

            entity.ToTable("CATEGORIESS");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Certificate>(entity =>
        {
            entity.HasKey(e => e.Cerid).HasName("PK__CERTIFIC__5D4205583D8E74AF");

            entity.ToTable("CERTIFICATES");

            entity.Property(e => e.Cerid).HasColumnName("CERID");
            entity.Property(e => e.Cername)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("CERName");
            entity.Property(e => e.Cerpic)
                .IsRequired()
                .HasMaxLength(350)
                .IsUnicode(false)
                .HasColumnName("CERPic");
            entity.Property(e => e.EarnedYear).HasDefaultValueSql("(datepart(year,getdate()))");
            entity.Property(e => e.InstatutionName)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Chatthread>(entity =>
        {
            entity.HasKey(e => e.ChatThreadId).HasName("PK__CHATTHRE__32405D65FD56707D");

            entity.ToTable("CHATTHREAD");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsBlocked).HasDefaultValue(false);
            entity.Property(e => e.LastMessageAt).HasColumnType("datetime");
            entity.Property(e => e.LastMessagePreview).HasMaxLength(500);

            entity.HasOne(d => d.User1).WithMany(p => p.ChatthreadUser1s)
                .HasForeignKey(d => d.User1Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Chat_User1");

            entity.HasOne(d => d.User2).WithMany(p => p.ChatthreadUser2s)
                .HasForeignKey(d => d.User2Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Chat_User2");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__COMMENTS__C3B4DFCAD68DFD97");

            entity.ToTable("COMMENTS");

            entity.Property(e => e.CommentText)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PostId).HasColumnName("PostID");

            entity.HasOne(d => d.Post).WithMany(p => p.Comments)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Comment_Post");

            entity.HasOne(d => d.User).WithMany(p => p.Comments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Comment_User");
        });

        modelBuilder.Entity<Diamond>(entity =>
        {
            entity.HasKey(e => e.Diamondid).HasName("PK__DIAMOND__0E6908ED2F4448F3");

            entity.ToTable("DIAMOND");

            entity.HasIndex(e => e.UserId, "UQ__DIAMOND__1788CC4DF3A3B250").IsUnique();

            entity.Property(e => e.Diamondid).HasColumnName("DIAMONDID");
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User)
                  .WithOne(p => p.Diamond)
                  .HasForeignKey<Diamond>(d => d.UserId)
                  .OnDelete(DeleteBehavior.ClientSetNull)
                  .HasConstraintName("FK_Diamond_User");
        });



        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.Feedbackid).HasName("PK__FEEDBACK__7074B31EE5D386DA");

            entity.ToTable("FEEDBACK");

            entity.Property(e => e.Feedbackid).HasColumnName("FEEDBACKID");
            entity.Property(e => e.Feedbackdetails)
                .HasMaxLength(400)
                .HasColumnName("FEEDBACKDETAILS");
            entity.Property(e => e.Feedbackrange).HasColumnName("FEEDBACKRANGE");
        });

        modelBuilder.Entity<Like>(entity =>
        {
            entity.HasKey(e => e.LikeId).HasName("PK__LIKES__A2922C147C9BB08F");

            entity.ToTable("LIKES");

            entity.HasIndex(e => new { e.UserId, e.PostId }, "UQ_Like").IsUnique();

            entity.Property(e => e.PostId).HasColumnName("PostID");

            entity.HasOne(d => d.Post).WithMany(p => p.Likes)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Like_Post");

            entity.HasOne(d => d.User).WithMany(p => p.Likes)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Like_User");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.HasKey(e => e.Materialid).HasName("PK__MATERIAL__278B51D52BAE0509");

            entity.ToTable("MATERIALS");

            entity.Property(e => e.Materialid).HasColumnName("MATERIALID");
            entity.Property(e => e.Cateid).HasColumnName("CATEID");
            entity.Property(e => e.Description).HasMaxLength(450);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("TITLE");
            entity.Property(e => e.Uploaderid).HasColumnName("UPLOADERID");

            entity.HasOne(d => d.Cate).WithMany(p => p.Materials)
                .HasForeignKey(d => d.Cateid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Material_Category");

            entity.HasOne(d => d.Uploader).WithMany(p => p.Materials)
                .HasForeignKey(d => d.Uploaderid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Material_User");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__NOTIFICA__20CF2E126A589282");

            entity.ToTable("NOTIFICATIONS");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Details)
                .IsRequired()
                .HasMaxLength(400);
            entity.Property(e => e.EntityType)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.ReadAt).HasColumnType("datetime");
            entity.Property(e => e.RedirectUrl)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("RedirectURL");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Sender).WithMany(p => p.NotificationSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK_Notification_Sender");

            entity.HasOne(d => d.User).WithMany(p => p.NotificationUsers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Notification_User");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.Packageid).HasName("PK__PACKAGE__35387D5009B32069");

            entity.ToTable("PACKAGE");

            entity.Property(e => e.Packageid).HasColumnName("PACKAGEId");
            entity.Property(e => e.Diamondpoints).HasColumnName("DIAMONDPoints");
            entity.Property(e => e.Packagedetails)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("PACKAGEDETAILS");
            entity.Property(e => e.Packageduration)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PACKAGEDURATION");
            entity.Property(e => e.Packagename)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("PACKAGENAME");
            entity.Property(e => e.Packageprice)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("PACKAGEPrice");
        });

        modelBuilder.Entity<Paymenttransaction>(entity =>
        {
            entity.HasKey(e => e.PayId).HasName("PK__PAYMENTT__EE8FCECF6395CEC7");

            entity.ToTable("PAYMENTTRANSACTION");

            entity.Property(e => e.Amount)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("AMOUNT");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("CURRENCY");
            entity.Property(e => e.GetwayTransactionId)
                .HasMaxLength(300)
                .HasColumnName("GetwayTransactionID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TransactionDate).HasDefaultValueSql("(getdate())");



        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__POSTS__AA12603883BF519D");

            entity.ToTable("POSTS");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.Content).HasMaxLength(1500);
            entity.Property(e => e.CreatedAt)
                        .HasDefaultValueSql("(getdate())")
                        .HasColumnType("datetime");
            entity.Property(e => e.SkillId).HasColumnName("SkillID");

            entity.HasOne(d => d.Skill).WithMany(p => p.Posts)
                        .HasForeignKey(d => d.SkillId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Post_Skill");

            entity.HasOne(d => d.User).WithMany(p => p.Posts)
                        .HasForeignKey(d => d.UserId)
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_Post_User");
        });

        modelBuilder.Entity<Postmedia>(entity =>
        {
            entity.HasKey(e => e.PmediaId).HasName("PK__POSTMEDI__6414C455D155CFFB");

            entity.ToTable("POSTMEDIAS");

            entity.Property(e => e.PmediaId).HasColumnName("PMediaId");
            entity.Property(e => e.EntityType)
                            .IsRequired()
                            .HasMaxLength(100)
                            .IsUnicode(false);
            entity.Property(e => e.MediaUrl)
                            .IsRequired()
                            .HasMaxLength(300)
                            .IsUnicode(false);
            entity.Property(e => e.PostId).HasColumnName("PostID");

            entity.HasOne(d => d.Post).WithMany(p => p.PostMedias)
                .HasForeignKey(d => d.PostId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PostMedia_Post");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__PROJECTS__761ABED038F8DFCE");

            entity.ToTable("PROJECTS");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.ProjectDesc).HasMaxLength(600);
            entity.Property(e => e.ProjectName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Repolink)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("REPOLink");

            entity.HasOne(d => d.User).WithMany(p => p.Projects)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Project_User");
        });

        modelBuilder.Entity<Report>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__REPORTS__D5BD4805BCF300B0");

            entity.ToTable("REPORTS");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.EntityType)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ReportDescription)
                .IsRequired()
                .HasMaxLength(500);

            entity.HasOne(d => d.ReportedByNavigation).WithMany(p => p.ReportReportedByNavigations)
                .HasForeignKey(d => d.ReportedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Report_By");

            entity.HasOne(d => d.ReportedUser).WithMany(p => p.ReportReportedUsers)
                .HasForeignKey(d => d.ReportedUserId)
                .HasConstraintName("FK_Report_User");
        });

        modelBuilder.Entity<Session>(entity =>
        {
            entity.HasKey(e => e.Sessionid).HasName("PK__SESSION__FC86FC5F062580BD");

            entity.ToTable("SESSION");

            entity.Property(e => e.Sessionid).HasColumnName("SESSIONId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ScheduleEnd).HasColumnType("datetime");
            entity.Property(e => e.ScheduleStart).HasColumnType("datetime");
            entity.Property(e => e.SkillId).HasColumnName("SkillID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Learner).WithMany(p => p.SessionLearners)
                .HasForeignKey(d => d.LearnerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Session_Learner");

            entity.HasOne(d => d.Skill).WithMany(p => p.Sessions)
                .HasForeignKey(d => d.SkillId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Session_Skill");

            entity.HasOne(d => d.Teacher).WithMany(p => p.SessionTeachers)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Session_Teacher");
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasKey(e => e.SkillId).HasName("PK__SKILLS__DFA09187E37E63C6");

            entity.ToTable("SKILLS");

            entity.Property(e => e.CateId).HasColumnName("CateID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Cate).WithMany(p => p.Skills)
                .HasForeignKey(d => d.CateId)
                .HasConstraintName("FK_Skill_Category");

          modelBuilder.Entity<UserSkills>()
    .HasKey(us => new { us.UserId, us.SkillId });

modelBuilder.Entity<UserSkills>()
    .HasOne(us => us.User)
    .WithMany(u => u.UserSkills)
    .HasForeignKey(us => us.UserId)
    .OnDelete(DeleteBehavior.ClientSetNull);

modelBuilder.Entity<UserSkills>()
    .HasOne(us => us.Skill)
    .WithMany(s => s.UserSkills)
    .HasForeignKey(us => us.SkillId)
    .OnDelete(DeleteBehavior.ClientSetNull);

        });

        modelBuilder.Entity<Socialmediaaccount>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__SOCIALME__349DA5A65744A42F");

            entity.ToTable("SOCIALMEDIAACCOUNTS");

            entity.Property(e => e.FacebookLink)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.Linkedin)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.PersonalWebsite)
                .HasMaxLength(400)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithMany(p => p.Socialmediaaccounts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SocialMedia_User");
        });

        modelBuilder.Entity<Userfeedback>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.FeedbackId }).HasName("PK_UserFeedback");

            entity.ToTable("USERFEEDBACK");

            entity.Property(e => e.SubmittedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Feedback).WithMany(p => p.Userfeedbacks)
                .HasForeignKey(d => d.FeedbackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFeedback_Feedback");

            entity.HasOne(d => d.User).WithMany(p => p.Userfeedbacks)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserFeedback_User");
        });

        modelBuilder.Entity<Usernationalid>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__USERNATI__3214EC078DE172F2");

            entity.ToTable("USERNATIONALID");

            entity.HasIndex(e => e.UserId, "UQ__USERNATI__1788CC4DF7CCB5C3").IsUnique();

            entity.Property(e => e.BackPic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.FrontPic)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.SelfieWithId)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);

            entity.HasOne(d => d.User).WithOne(p => p.Usernationalid)
                .HasForeignKey<Usernationalid>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserNationalID_User");
        });

        modelBuilder.Entity<Usersessionfeedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__USERSESS__6A4BEDD62089FA43");

            entity.ToTable("USERSESSIONFEEDBACKS");

            entity.Property(e => e.Comment)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.RatedByUser).WithMany(p => p.UsersessionfeedbackRatedByUsers)
                .HasForeignKey(d => d.RatedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Feedback_ByUser");

            entity.HasOne(d => d.RatedToUser).WithMany(p => p.UsersessionfeedbackRatedToUsers)
                .HasForeignKey(d => d.RatedToUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Feedback_ToUser");

            entity.HasOne(d => d.Session).WithMany(p => p.Usersessionfeedbacks)
                .HasForeignKey(d => d.SessionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Feedback_Session");
        });

        modelBuilder.Entity<Usersprofile>(entity =>
        {

            entity.HasOne(u => u.Diamond)
        .WithOne(d => d.User)
        .HasForeignKey<Diamond>(d => d.UserId)
        .HasConstraintName("FK_User_Diamond");

            entity.HasKey(e => e.UserId).HasName("PK__USERSPRO__1788CC4C54A710E3");

            entity.ToTable("USERSPROFILE");

            entity.Property(e => e.Authuserid)
                .HasMaxLength(450)
                .IsUnicode(false)
                .HasColumnName("AUTHUSERID");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ExperienceText).HasMaxLength(600);
            entity.Property(e => e.Fname)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Lname)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ProfilePic).HasMaxLength(500);


        });

        modelBuilder.Entity<PremiumSubscriber>(entity =>
        {
            entity.HasKey(ps => new { ps.UserId, ps.PackageId });

            entity.HasOne(ps => ps.Users)
                .WithMany(u => u.PremiumSubscribers)
                .HasForeignKey(ps => ps.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PremiumSubscriber_User");

            entity.HasOne(ps => ps.Package)
                .WithMany(p => p.PremiumSubscribers)
                .HasForeignKey(ps => ps.PackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PremiumSubscriber_Package");

            entity.ToTable("PremiumSubscriber");
        });
        modelBuilder.Entity<UserSkills>()
    .HasKey(us => new { us.UserId, us.SkillId });

        modelBuilder.Entity<UserSkills>()
            .HasOne(us => us.User)
            .WithMany(u => u.UserSkills) 
            .HasForeignKey(us => us.UserId);

        modelBuilder.Entity<UserSkills>()
            .HasOne(us => us.Skill)
            .WithMany(s => s.UserSkills) 
            .HasForeignKey(us => us.SkillId);

        OnModelCreatingPartial(modelBuilder);

    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}